import PageHeader from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { formatDate, formatMoney } from "@/lib/format";
import type { Client } from "../../../drizzle/schema";
import { Building2, FileText, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type ClientForm = { name: string; email: string; address: string; phone: string; taxId: string };
const emptyClient: ClientForm = { name: "", email: "", address: "", phone: "", taxId: "" };

export default function Clients() {
  const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Client | null | "new">(null); const [form, setForm] = useState<ClientForm>(emptyClient); const [selected, setSelected] = useState<number | null>(null);
  const utils = trpc.useUtils(); const clients = trpc.clients.list.useQuery({ query }); const detail = trpc.clients.get.useQuery({ id: selected || 1 }, { enabled: Boolean(selected) });
  const create = trpc.clients.create.useMutation({ onSuccess: () => { utils.clients.list.invalidate(); toast.success("Klien disimpan."); close(); }, onError: error => toast.error(error.message) });
  const update = trpc.clients.update.useMutation({ onSuccess: () => { utils.clients.list.invalidate(); toast.success("Data klien diperbarui."); close(); }, onError: error => toast.error(error.message) });
  const remove = trpc.clients.remove.useMutation({ onSuccess: () => { utils.clients.list.invalidate(); toast.success("Klien dihapus."); if (selected) setSelected(null); }, onError: error => toast.error(error.message) });
  const close = () => { setEditing(null); setForm(emptyClient); };
  const openNew = () => { setEditing("new"); setForm(emptyClient); };
  const openEdit = (client: Client) => { setEditing(client); setForm({ name: client.name, email: client.email || "", address: client.address || "", phone: client.phone || "", taxId: client.taxId || "" }); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data = { ...form, address: form.address || null, phone: form.phone || null, taxId: form.taxId || null }; if (editing === "new") create.mutate(data); else if (editing) update.mutate({ id: editing.id, data }); };
  return <><PageHeader eyebrow="Direktori" title="Klien" description="Simpan informasi klien dan lihat riwayat invoice mereka." action={<Button className="gap-2" onClick={openNew}><Plus className="size-4" />Tambah klien</Button>} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="overflow-hidden rounded-xl border border-slate-200/80 bg-white"><div className="border-b p-4"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Cari nama atau email klien…" className="pl-9" /></div></div>{clients.isLoading ? <div className="p-6 text-sm text-muted-foreground">Memuat klien…</div> : !clients.data?.length ? <div className="px-6 py-16 text-center"><Building2 className="mx-auto size-9 text-slate-300" /><h2 className="mt-4 font-bold">Belum ada klien</h2><p className="mt-1 text-sm text-muted-foreground">Tambahkan klien pertama untuk mulai membuat invoice.</p><Button size="sm" className="mt-5" onClick={openNew}>Tambah klien</Button></div> : <div className="divide-y divide-slate-100">{clients.data.map(client => <button key={client.id} onClick={() => setSelected(client.id)} className={`flex w-full items-center gap-4 px-5 py-4 text-left transition-colors hover:bg-slate-50 ${selected === client.id ? "bg-blue-50/70" : ""}`}><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-sm font-bold text-primary">{client.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-800">{client.name}</p><p className="mt-0.5 truncate text-sm text-muted-foreground">{client.email || "Tanpa email"}</p></div><Button type="button" size="icon" variant="ghost" onClick={event => { event.stopPropagation(); openEdit(client); }}><Pencil className="size-4" /></Button></button>)}</div>}</section>
      <aside className="rounded-xl border border-slate-200/80 bg-white p-5 sm:p-6">{detail.isLoading && selected ? <p className="text-sm text-muted-foreground">Memuat detail klien…</p> : detail.data ? <><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-primary">Detail klien</p><h2 className="mt-2 text-xl font-bold tracking-tight">{detail.data.name}</h2></div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => { const client = detail.data; if (client) openEdit(client); }}><Pencil className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => { const client = detail.data; if (client && window.confirm(`Hapus ${client.name}?`)) remove.mutate({ id: client.id }); }}><Trash2 className="size-4 text-rose-600" /></Button></div></div><div className="mt-6 space-y-3 text-sm"><Info label="Email" value={detail.data.email} /><Info label="Telepon" value={detail.data.phone} /><Info label="Alamat" value={detail.data.address} /><Info label="NPWP" value={detail.data.taxId || "—"} /></div><div className="mt-7 border-t pt-5"><div className="flex items-center justify-between"><h3 className="font-bold">Riwayat invoice</h3><span className="text-xs font-semibold text-muted-foreground">{detail.data.invoices.length} invoice</span></div>{detail.data.invoices.length ? <div className="mt-4 space-y-3">{detail.data.invoices.slice(0, 5).map(invoice => <div key={invoice.id} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-primary">{invoice.invoiceNumber}</p><p className="mt-0.5 text-xs text-muted-foreground">{formatDate(invoice.invoiceDate)}</p></div><p className="text-sm font-semibold">{formatMoney(invoice.total, invoice.currency)}</p></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">Belum ada invoice untuk klien ini.</p>}</div></> : <div className="grid min-h-72 place-items-center text-center"><div><FileText className="mx-auto size-8 text-slate-300" /><p className="mt-3 text-sm text-muted-foreground">Pilih klien untuk melihat detail dan riwayat invoice.</p></div></div>}</aside></div>
    <Dialog open={editing !== null} onOpenChange={open => !open && close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{editing === "new" ? "Tambah klien" : "Edit klien"}</DialogTitle><DialogDescription>NPWP bersifat opsional dan dapat diisi apabila diperlukan.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={submit}><div className="space-y-1.5"><Label>Nama klien</Label><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Email</Label><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></div><div className="space-y-1.5"><Label>Telepon</Label><Input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></div></div><div className="space-y-1.5"><Label>Alamat</Label><Textarea value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></div><div className="space-y-1.5"><Label>NPWP <span className="font-normal text-muted-foreground">(opsional)</span></Label><Input value={form.taxId} onChange={event => setForm({ ...form, taxId: event.target.value })} /></div><div className="mt-2 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={close}>Batal</Button><Button type="submit" disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? "Menyimpan…" : "Simpan klien"}</Button></div></form></DialogContent></Dialog>
  </>;
}

function Info({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-xs font-semibold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 whitespace-pre-line leading-5 text-slate-700">{value || "—"}</p></div>; }
