import PageHeader from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { formatMoney } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, MapPin, PackageSearch, Search, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type Destination = { id: number; label: string; province_name?: string; city_name?: string; district_name?: string; subdistrict_name?: string; zip_code?: string };
type ShippingPayload = { data?: Array<{ name?: string; code?: string; service?: string; description?: string; cost?: number | string; etd?: string }> };
type TrackingPayload = { data?: { delivered?: boolean; summary?: { courier_name?: string; courier_code?: string; waybill_number?: string; service_code?: string; status?: string; origin?: string; destination?: string }; delivery_status?: { status?: string; pod_receiver?: string; pod_date?: string; pod_time?: string }; manifest?: Array<{ manifest_description?: string; manifest_date?: string; manifest_time?: string; city_name?: string }> } };

function useDebouncedValue(value: string, delay = 450) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = window.setTimeout(() => setDebounced(value), delay); return () => window.clearTimeout(timer); }, [value, delay]); return debounced; }

function DestinationPicker({ label, query, setQuery, selected, setSelected }: { label: string; query: string; setQuery: (value: string) => void; selected: Destination | null; setSelected: (value: Destination | null) => void }) {
  const debounced = useDebouncedValue(query);
  const shippingTrpc = trpc as unknown as { shipping: { searchDestination: { useQuery: (input: { query: string }, options: { enabled: boolean }) => { data?: { data?: Destination[] }; isFetching: boolean } } } };
  const search = shippingTrpc.shipping.searchDestination.useQuery({ query: debounced || "--" }, { enabled: debounced.trim().length >= 3 });
  const options = search.data?.data || [];
  return <div className="space-y-2"><Label>{label}</Label><div className="relative"><Input value={query} onChange={event => { setQuery(event.target.value); setSelected(null); }} placeholder="Ketik kecamatan, kota, atau kode pos" /><MapPin className="absolute right-3 top-3 size-4 text-slate-400" /></div>{selected ? <div className="flex items-center justify-between gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800"><span className="line-clamp-2 font-medium">{selected.label}</span><button className="shrink-0 font-semibold underline" onClick={() => setSelected(null)}>Ubah</button></div> : debounced.trim().length >= 3 && <div className="max-h-44 overflow-auto rounded-lg border bg-white shadow-sm">{search.isFetching ? <p className="px-3 py-3 text-xs text-muted-foreground">Mencari lokasi…</p> : options.length ? options.map(option => <button key={option.id} className="block w-full border-b border-slate-100 px-3 py-2.5 text-left text-xs hover:bg-slate-50 last:border-0" onClick={() => { setSelected(option); setQuery(option.label); }}><span className="font-semibold text-slate-800">{option.label}</span>{option.zip_code && <span className="ml-2 text-slate-500">{option.zip_code}</span>}</button>) : <p className="px-3 py-3 text-xs text-muted-foreground">Lokasi tidak ditemukan.</p>}</div>}</div>;
}

export default function ShippingTools() {
  const invoiceId = useMemo(() => Number(new URLSearchParams(window.location.search).get("invoice")) || null, []);
  const invoice = trpc.invoices.get.useQuery({ id: invoiceId || 1 }, { enabled: Boolean(invoiceId) });
  const [originQuery, setOriginQuery] = useState(""); const [destinationQuery, setDestinationQuery] = useState("");
  const [origin, setOrigin] = useState<Destination | null>(null); const [destination, setDestination] = useState<Destination | null>(null);
  const [weight, setWeight] = useState("1000"); const [couriers, setCouriers] = useState("jne:jnt:sicepat:anteraja:pos");
  const [courier, setCourier] = useState(""); const [trackingNumber, setTrackingNumber] = useState(""); const [lastPhoneDigits, setLastPhoneDigits] = useState("");
  type QuoteMutation = { isPending: boolean; data?: ShippingPayload; mutate: (input: { originId: number; destinationId: number; weight: number; couriers: string }, options: { onError: (error: { message: string }) => void }) => void };
  type TrackMutation = { isPending: boolean; data?: TrackingPayload; mutate: (input: { courier: string; trackingNumber: string; lastPhoneDigits?: string }, options: { onError: (error: { message: string }) => void }) => void };
  const shippingTrpc = trpc as unknown as { shipping: { calculate: { useMutation: () => QuoteMutation }; track: { useMutation: () => TrackMutation } } };
  const quote = shippingTrpc.shipping.calculate.useMutation();
  const track = shippingTrpc.shipping.track.useMutation();
  useEffect(() => { const data = invoice.data as { invoice?: { courierName?: string | null; trackingNumber?: string | null } } | undefined; if (!data?.invoice) return; setCourier(data.invoice.courierName || ""); setTrackingNumber(data.invoice.trackingNumber || ""); }, [invoice.data]);
  const quoteRows = quote.data?.data || []; const tracking = track.data?.data;
  return <><PageHeader eyebrow="Layanan pengiriman" title="Cek ongkir & resi" description="Bandingkan ongkir dengan lokasi yang tepat, lalu lacak resi yang sudah tersimpan pada invoice." />
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card className="border-slate-200/80"><CardContent className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-primary"><PackageSearch className="size-5" /></div><div><h2 className="font-bold">Cek ongkir domestik</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Pilih asal dan tujuan hingga tingkat wilayah, masukkan berat dalam gram, lalu bandingkan layanan kurir.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><DestinationPicker label="Lokasi asal" query={originQuery} setQuery={setOriginQuery} selected={origin} setSelected={setOrigin} /><DestinationPicker label="Lokasi tujuan" query={destinationQuery} setQuery={setDestinationQuery} selected={destination} setSelected={setDestination} /><div className="space-y-2"><Label>Berat paket (gram)</Label><Input type="number" min="1" value={weight} onChange={event => setWeight(event.target.value)} /></div><div className="space-y-2"><Label>Kode kurir</Label><Input value={couriers} onChange={event => setCouriers(event.target.value)} placeholder="jne:jnt:sicepat" /><p className="text-xs text-muted-foreground">Pisahkan beberapa kode dengan tanda titik dua.</p></div></div><Button className="mt-5 gap-2" disabled={quote.isPending || !origin || !destination || Number(weight) < 1} onClick={() => { if (!origin || !destination) return; quote.mutate({ originId: origin.id, destinationId: destination.id, weight: Number(weight), couriers }, { onError: error => toast.error(error.message) }); }}><Search className="size-4" />{quote.isPending ? "Memeriksa ongkir…" : "Cek ongkir"}</Button>{quoteRows.length > 0 && <div className="mt-6 overflow-hidden rounded-xl border border-slate-200"><div className="grid grid-cols-[1.1fr_.8fr_.6fr] gap-3 bg-slate-50 px-4 py-3 text-[11px] font-bold uppercase tracking-[.08em] text-slate-500"><span>Layanan</span><span>Estimasi</span><span className="text-right">Ongkir</span></div>{quoteRows.map((row, index) => <div key={`${row.code}-${row.service}-${index}`} className="grid grid-cols-[1.1fr_.8fr_.6fr] gap-3 border-t border-slate-100 px-4 py-3 text-sm"><div><p className="font-semibold text-slate-800">{row.name || row.code} {row.service}</p><p className="mt-0.5 text-xs text-slate-500">{row.description || row.code}</p></div><span className="text-slate-600">{row.etd || "—"}</span><span className="text-right font-bold text-slate-900">{formatMoney(Number(row.cost || 0))}</span></div>)}</div>}</CardContent></Card>
      <Card className="border-slate-200/80"><CardContent className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Truck className="size-5" /></div><div><h2 className="font-bold">Cek resi</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Masukkan kode kurir dan nomor resi. Jika datang dari preview invoice, keduanya sudah terisi otomatis.</p></div></div><div className="mt-6 grid gap-4"><div className="space-y-2"><Label>Kode kurir</Label><Input value={courier} onChange={event => setCourier(event.target.value)} placeholder="Contoh: jne, jnt, sicepat" /></div><div className="space-y-2"><Label>Nomor resi</Label><Input value={trackingNumber} onChange={event => setTrackingNumber(event.target.value)} placeholder="Masukkan nomor resi" /></div><div className="space-y-2"><Label>5 digit akhir telepon penerima <span className="font-normal text-muted-foreground">(bila diminta kurir)</span></Label><Input inputMode="numeric" maxLength={5} value={lastPhoneDigits} onChange={event => setLastPhoneDigits(event.target.value.replace(/\D/g, "").slice(0, 5))} placeholder="Opsional" /></div></div><Button className="mt-5 gap-2" disabled={track.isPending || courier.trim().length < 2 || trackingNumber.trim().length < 4} onClick={() => track.mutate({ courier, trackingNumber, ...(lastPhoneDigits.length === 5 ? { lastPhoneDigits } : {}) }, { onError: error => toast.error(error.message) })}><Search className="size-4" />{track.isPending ? "Melacak resi…" : "Cek resi"}</Button>{tracking && <div className="mt-6 space-y-4"><div className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.08em] text-emerald-700">Status pengiriman</p><p className="mt-1 text-lg font-bold text-emerald-950">{tracking.summary?.status || tracking.delivery_status?.status || "Dalam proses"}</p><p className="mt-1 text-sm text-emerald-800">{tracking.summary?.courier_name || tracking.summary?.courier_code} · {tracking.summary?.waybill_number}</p></div>{tracking.delivered && <Badge className="bg-emerald-700">Terkirim</Badge>}</div></div>{tracking.manifest?.length ? <div><p className="mb-3 text-sm font-bold text-slate-800">Riwayat perjalanan</p><div className="space-y-3">{tracking.manifest.map((item, index) => <div key={`${item.manifest_date}-${item.manifest_time}-${index}`} className="relative border-l border-slate-200 pl-4 text-sm before:absolute before:-left-1 before:top-1.5 before:size-2 before:rounded-full before:bg-primary"><p className="font-medium text-slate-800">{item.manifest_description}</p><p className="mt-1 text-xs text-slate-500">{[item.manifest_date, item.manifest_time, item.city_name].filter(Boolean).join(" · ")}</p></div>)}</div></div> : <Separator />}</div>}</CardContent></Card></div></>;
}
