import InvoiceStatusBadge from "@/components/InvoiceStatusBadge";
import { formatDate, formatMoney } from "@/lib/format";
import type { InvoiceStatus } from "@shared/invoice";

export type InvoiceDocumentData = {
  invoice: {
    id: number; invoiceNumber: string; invoiceDate: Date; dueDate: Date; status: InvoiceStatus;
    currency: string; subtotal: number; discount: number; taxRate: number; taxAmount: number; total: number; notes: string | null; publicId: string;
  };
  client: { name: string; email: string | null; address: string | null; phone: string | null; taxId?: string | null };
  business: { businessName: string; address: string | null; email: string | null; phone: string | null; bankName: string | null; bankAccountName: string | null; bankAccountNumber: string | null; logoUrl: string | null; accentColor: string; invoiceTemplate: "clean" | "modern" | "classic" };
  items: { id?: number; description: string; quantity: number; unitPrice: number; subtotal: number }[];
};

function AddressBlock({ lines }: { lines: (string | null | undefined)[] }) {
  return <div className="space-y-1 text-sm leading-5 text-slate-600">{lines.filter(Boolean).map((line, index) => <p key={`${line}-${index}`}>{line}</p>)}</div>;
}

export default function InvoiceDocument({ data, publicView = false }: { data: InvoiceDocumentData; publicView?: boolean }) {
  const { invoice, client, business, items } = data;
  const tone = business.accentColor || "#0C2B63";
  return <article id="invoice-document" className="invoice-paper mx-auto w-full max-w-[820px] bg-white p-7 sm:p-10 md:p-14" style={{ borderTop: business.invoiceTemplate === "modern" ? `8px solid ${tone}` : undefined }}>
    <header className="flex flex-col justify-between gap-8 border-b border-slate-200 pb-8 sm:flex-row">
      <div className="flex items-start gap-3"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-lg bg-slate-100 text-lg font-bold" style={{ color: tone }}>{business.logoUrl ? <img src={business.logoUrl} alt={`Logo ${business.businessName}`} className="size-full object-cover" /> : business.businessName.slice(0, 1).toUpperCase()}</div><div><h1 className="text-lg font-bold text-slate-900">{business.businessName}</h1><AddressBlock lines={[business.address, business.email, business.phone]} /></div></div>
      <div className="sm:text-right"><div className="mb-3 flex items-center gap-3 sm:justify-end"><h2 className="text-3xl font-bold tracking-tight" style={{ color: tone }}>INVOICE</h2>{publicView && <InvoiceStatusBadge status={invoice.status} />}</div><div className="grid grid-cols-2 gap-x-8 text-left text-xs sm:text-right"><div><p className="font-semibold uppercase tracking-[.1em] text-slate-400">Nomor invoice</p><p className="mt-1 font-semibold text-slate-800">{invoice.invoiceNumber}</p></div><div><p className="font-semibold uppercase tracking-[.1em] text-slate-400">Jatuh tempo</p><p className="mt-1 font-semibold text-slate-800">{formatDate(invoice.dueDate)}</p></div></div></div>
    </header>
    <section className="grid gap-8 py-8 sm:grid-cols-2"><div><p className="mb-3 text-[11px] font-bold uppercase tracking-[.13em] text-slate-400">Dari</p><p className="mb-1 font-semibold text-slate-900">{business.businessName}</p><AddressBlock lines={[business.address, business.email, business.phone]} /></div><div><p className="mb-3 text-[11px] font-bold uppercase tracking-[.13em] text-slate-400">Ditagihkan kepada</p><p className="mb-1 font-semibold text-slate-900">{client.name}</p><AddressBlock lines={[client.address, client.email, client.phone, client.taxId ? `NPWP: ${client.taxId}` : null]} /></div></section>
    <section className="overflow-hidden rounded-lg border border-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-[.11em] text-slate-500"><tr><th className="px-4 py-3 sm:px-5">Deskripsi</th><th className="px-3 py-3 text-center">Qty</th><th className="hidden px-3 py-3 text-right sm:table-cell">Harga</th><th className="px-4 py-3 text-right sm:px-5">Subtotal</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.description}-${index}`} className="border-t border-slate-100"><td className="px-4 py-4 font-medium text-slate-800 sm:px-5">{item.description}<span className="mt-1 block text-xs font-normal text-slate-500 sm:hidden">{formatMoney(item.unitPrice, invoice.currency)} / item</span></td><td className="px-3 py-4 text-center text-slate-600">{item.quantity}</td><td className="hidden px-3 py-4 text-right text-slate-600 sm:table-cell">{formatMoney(item.unitPrice, invoice.currency)}</td><td className="px-4 py-4 text-right font-semibold text-slate-800 sm:px-5">{formatMoney(item.subtotal, invoice.currency)}</td></tr>)}</tbody></table></section>
    <section className="mt-7 flex flex-col gap-8 sm:flex-row sm:justify-between"><div className="max-w-sm"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-slate-400">Catatan</p><p className="mt-3 text-sm leading-6 text-slate-600">{invoice.notes || "Terima kasih atas kepercayaan Anda. Mohon lakukan pembayaran sebelum tanggal jatuh tempo."}</p></div><div className="w-full max-w-[280px] self-end"><div className="space-y-3 text-sm"><div className="flex justify-between text-slate-600"><span>Subtotal</span><span>{formatMoney(invoice.subtotal, invoice.currency)}</span></div>{invoice.discount > 0 && <div className="flex justify-between text-slate-600"><span>Diskon</span><span>-{formatMoney(invoice.discount, invoice.currency)}</span></div>}<div className="flex justify-between text-slate-600"><span>Pajak ({invoice.taxRate}%)</span><span>{formatMoney(invoice.taxAmount, invoice.currency)}</span></div></div><div className="mt-4 flex justify-between border-t-2 pt-4 text-xl font-bold" style={{ borderColor: tone, color: tone }}><span>Total</span><span>{formatMoney(invoice.total, invoice.currency)}</span></div></div></section>
    {(business.bankName || business.bankAccountNumber) && <section className="mt-9 border-t border-slate-200 pt-6"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-slate-400">Informasi pembayaran</p><div className="mt-3 rounded-lg bg-slate-50 p-4 text-sm"><p className="font-semibold text-slate-800">{business.bankName || "Rekening pembayaran"}</p><p className="mt-1 text-slate-600">{business.bankAccountNumber}{business.bankAccountName ? ` a/n ${business.bankAccountName}` : ""}</p></div></section>}
  </article>;
}
