begin;

create type public.organization_member_role as enum ('owner', 'admin', 'staff');

create table public.organizations (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(120) unique,
  "createdByUserId" integer not null references public.users(id) on delete restrict,
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create table public."organizationMembers" (
  id integer generated by default as identity primary key,
  "organizationId" integer not null references public.organizations(id) on delete cascade,
  "userId" integer not null references public.users(id) on delete cascade,
  role public.organization_member_role not null default 'staff',
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now()),
  constraint organization_member_unique unique ("organizationId", "userId")
);

create table public."userActiveOrganizations" (
  "userId" integer primary key references public.users(id) on delete cascade,
  "organizationId" integer not null references public.organizations(id) on delete cascade,
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create table public."organizationInvitations" (
  id integer generated by default as identity primary key,
  "organizationId" integer not null references public.organizations(id) on delete cascade,
  email varchar(320) not null,
  role public.organization_member_role not null default 'staff',
  "tokenHash" char(64) not null unique,
  "invitedByUserId" integer not null references public.users(id) on delete restrict,
  "expiresAt" timestamptz not null,
  "acceptedAt" timestamptz,
  "createdAt" timestamptz not null default timezone('utc', now()),
  constraint invitation_role_not_owner check (role <> 'owner')
);

alter table public."businessProfiles" add column "organizationId" integer references public.organizations(id) on delete cascade;
alter table public.clients add column "organizationId" integer references public.organizations(id) on delete cascade;
alter table public."catalogItems" add column "organizationId" integer references public.organizations(id) on delete cascade;
alter table public.invoices add column "organizationId" integer references public.organizations(id) on delete cascade;
alter table public."invoiceActivities" add column "organizationId" integer references public.organizations(id) on delete cascade;

insert into public.organizations (name, "createdByUserId")
select coalesce(nullif(trim(bp."businessName"), ''), 'Bisnis Anda'), bp."userId"
from public."businessProfiles" bp
where not exists (
  select 1 from public.organizations o where o."createdByUserId" = bp."userId"
);

insert into public.organizations (name, "createdByUserId")
select coalesce(nullif(trim(u.name), ''), 'Bisnis Anda'), u.id
from public.users u
where not exists (
  select 1 from public.organizations o where o."createdByUserId" = u.id
);

insert into public."organizationMembers" ("organizationId", "userId", role)
select o.id, o."createdByUserId", 'owner'
from public.organizations o
on conflict ("organizationId", "userId") do nothing;

insert into public."userActiveOrganizations" ("userId", "organizationId")
select o."createdByUserId", o.id
from public.organizations o
on conflict ("userId") do update set "organizationId" = excluded."organizationId", "updatedAt" = timezone('utc', now());

update public."businessProfiles" bp set "organizationId" = o.id
from public.organizations o where o."createdByUserId" = bp."userId" and bp."organizationId" is null;
update public.clients c set "organizationId" = o.id
from public.organizations o where o."createdByUserId" = c."userId" and c."organizationId" is null;
update public."catalogItems" ci set "organizationId" = o.id
from public.organizations o where o."createdByUserId" = ci."userId" and ci."organizationId" is null;
update public.invoices i set "organizationId" = o.id
from public.organizations o where o."createdByUserId" = i."userId" and i."organizationId" is null;
update public."invoiceActivities" ia set "organizationId" = o.id
from public.organizations o where o."createdByUserId" = ia."userId" and ia."organizationId" is null;

alter table public."businessProfiles" alter column "organizationId" set not null;
alter table public.clients alter column "organizationId" set not null;
alter table public."catalogItems" alter column "organizationId" set not null;
alter table public.invoices alter column "organizationId" set not null;
alter table public."invoiceActivities" alter column "organizationId" set not null;

alter table public."businessProfiles" drop constraint if exists "businessProfiles_userId_key";
drop index if exists public.business_profile_organization_unique;
create unique index business_profile_organization_unique on public."businessProfiles" ("organizationId");
alter table public.invoices drop constraint if exists invoice_user_number_unique;
alter table public.invoices add constraint invoice_organization_number_unique unique ("organizationId", "invoiceNumber");

create index clients_organization_created_idx on public.clients ("organizationId", "createdAt");
create index catalog_organization_created_idx on public."catalogItems" ("organizationId", "createdAt");
create index invoice_organization_date_idx on public.invoices ("organizationId", "invoiceDate");
create index invoice_organization_client_idx on public.invoices ("organizationId", "clientId");
create index invoice_organization_batch_idx on public.invoices ("organizationId", "bulkBatchId");
create index invoice_activity_organization_created_idx on public."invoiceActivities" ("organizationId", "createdAt");
create index organization_member_user_idx on public."organizationMembers" ("userId", "organizationId");
create index organization_invitation_lookup_idx on public."organizationInvitations" (lower(email), "organizationId") where "acceptedAt" is null;

create or replace function public.current_faktur_organization_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select "organizationId" from public."userActiveOrganizations" where "userId" = public.current_faktur_user_id()),
    (select "organizationId" from public."organizationMembers" where "userId" = public.current_faktur_user_id() order by "createdAt" asc limit 1)
  );
$$;

create or replace function public.current_faktur_organization_role()
returns public.organization_member_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public."organizationMembers"
  where "organizationId" = public.current_faktur_organization_id()
    and "userId" = public.current_faktur_user_id()
  limit 1;
$$;

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer;
  v_organization_id integer;
begin
  insert into public.users ("authUserId", "openId", name, email, "loginMethod", role)
  values (
    new.id,
    new.id::text,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, new.id::text), '@', 1)),
    new.email,
    coalesce(new.raw_app_meta_data ->> 'provider', 'email'),
    'user'
  )
  on conflict ("authUserId") do update
    set name = excluded.name,
        email = excluded.email,
        "loginMethod" = excluded."loginMethod",
        "lastSignedIn" = timezone('utc', now())
  returning id into v_user_id;

  insert into public.organizations (name, "createdByUserId")
  select coalesce(nullif(trim(new.raw_user_meta_data ->> 'company_name'), ''), coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, new.id::text), '@', 1), 'Bisnis Anda')), v_user_id
  where not exists (select 1 from public.organizations where "createdByUserId" = v_user_id)
  returning id into v_organization_id;

  if v_organization_id is null then
    select id into v_organization_id from public.organizations where "createdByUserId" = v_user_id order by id asc limit 1;
  end if;

  insert into public."organizationMembers" ("organizationId", "userId", role)
  values (v_organization_id, v_user_id, 'owner')
  on conflict ("organizationId", "userId") do nothing;

  insert into public."userActiveOrganizations" ("userId", "organizationId")
  values (v_user_id, v_organization_id)
  on conflict ("userId") do update set "organizationId" = excluded."organizationId", "updatedAt" = timezone('utc', now());

  return new;
end;
$$;

create trigger organizations_set_updated_at before update on public.organizations
for each row execute function public.set_updated_at();
create trigger organization_members_set_updated_at before update on public."organizationMembers"
for each row execute function public.set_updated_at();
create trigger user_active_organizations_set_updated_at before update on public."userActiveOrganizations"
for each row execute function public.set_updated_at();

alter table public.organizations enable row level security;
alter table public."organizationMembers" enable row level security;
alter table public."userActiveOrganizations" enable row level security;
alter table public."organizationInvitations" enable row level security;

create policy "organizations_select_member" on public.organizations
  for select using (exists (
    select 1 from public."organizationMembers" m
    where m."organizationId" = organizations.id and m."userId" = public.current_faktur_user_id()
  ));
create policy "organization_members_select_self" on public."organizationMembers"
  for select using ("userId" = public.current_faktur_user_id());
create policy "active_organization_own" on public."userActiveOrganizations"
  for all using ("userId" = public.current_faktur_user_id()) with check (
    "userId" = public.current_faktur_user_id() and exists (
      select 1 from public."organizationMembers" m
      where m."organizationId" = "userActiveOrganizations"."organizationId"
        and m."userId" = public.current_faktur_user_id()
    )
  );

revoke execute on function public.current_faktur_organization_id() from public, anon;
revoke execute on function public.current_faktur_organization_role() from public, anon;
grant execute on function public.current_faktur_organization_id() to authenticated;
grant execute on function public.current_faktur_organization_role() to authenticated;

commit;
