begin;

create type public.user_role as enum ('user', 'admin');
create type public.invoice_template as enum ('clean', 'modern', 'classic');
create type public.invoice_status as enum ('draft', 'sent', 'unpaid', 'paid', 'overdue', 'cancelled');
create type public.discount_type as enum ('amount', 'percentage');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new."updatedAt" = timezone('utc', now());
  return new;
end;
$$;

create table public.users (
  id integer generated by default as identity primary key,
  "authUserId" uuid unique,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now()),
  "lastSignedIn" timestamptz not null default timezone('utc', now())
);

create table public."businessProfiles" (
  id integer generated by default as identity primary key,
  "userId" integer not null unique references public.users(id) on delete cascade,
  "businessName" varchar(255) not null,
  address text,
  email varchar(320),
  phone varchar(50),
  "bankName" varchar(100),
  "bankAccountName" varchar(255),
  "bankAccountNumber" varchar(100),
  "logoUrl" text,
  "accentColor" varchar(16) not null default '#0C2B63',
  "invoiceTemplate" public.invoice_template not null default 'clean',
  "invoiceNumberFormat" varchar(80) not null default 'INV-{YYYY}-{SEQ}',
  "defaultTaxRate" integer not null default 11,
  "defaultCurrency" varchar(3) not null default 'IDR',
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create table public.clients (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  name varchar(255) not null,
  email varchar(320),
  address text,
  phone varchar(50),
  "taxId" varchar(100),
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create index clients_user_created_idx on public.clients ("userId", "createdAt");

create table public."catalogItems" (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  name varchar(255) not null,
  description text,
  "defaultPrice" integer not null default 0,
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now())
);

create index catalog_user_created_idx on public."catalogItems" ("userId", "createdAt");

create table public.invoices (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "clientId" integer not null references public.clients(id) on delete restrict,
  "invoiceNumber" varchar(80) not null,
  "invoiceDate" timestamptz not null,
  "dueDate" timestamptz not null,
  status public.invoice_status not null default 'draft',
  currency varchar(3) not null default 'IDR',
  subtotal integer not null default 0,
  discount integer not null default 0,
  "discountType" public.discount_type not null default 'amount',
  "discountValue" integer not null default 0,
  "taxRate" integer not null default 0,
  "taxAmount" integer not null default 0,
  total integer not null default 0,
  notes text,
  "storeNumber" varchar(100),
  "shippingAddress" text,
  "bulkBatchId" varchar(32),
  "isBatchSummary" boolean not null default false,
  "publicId" varchar(32) not null unique,
  "sentAt" timestamptz,
  "paidAt" timestamptz,
  "createdAt" timestamptz not null default timezone('utc', now()),
  "updatedAt" timestamptz not null default timezone('utc', now()),
  constraint invoice_user_number_unique unique ("userId", "invoiceNumber")
);

create index invoice_user_date_idx on public.invoices ("userId", "invoiceDate");
create index invoice_user_client_idx on public.invoices ("userId", "clientId");
create index invoice_user_batch_idx on public.invoices ("userId", "bulkBatchId");

create table public."invoiceItems" (
  id integer generated by default as identity primary key,
  "invoiceId" integer not null references public.invoices(id) on delete cascade,
  "catalogItemId" integer references public."catalogItems"(id) on delete set null,
  description varchar(500) not null,
  quantity integer not null default 1,
  "unitPrice" integer not null default 0,
  subtotal integer not null default 0,
  position integer not null default 0
);

create table public."invoiceActivities" (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "invoiceId" integer not null references public.invoices(id) on delete cascade,
  action varchar(48) not null,
  description text not null,
  "createdAt" timestamptz not null default timezone('utc', now())
);

create index invoice_activity_user_created_idx on public."invoiceActivities" ("userId", "createdAt");
create index invoice_activity_invoice_created_idx on public."invoiceActivities" ("invoiceId", "createdAt");

create trigger users_set_updated_at before update on public.users
for each row execute function public.set_updated_at();
create trigger business_profiles_set_updated_at before update on public."businessProfiles"
for each row execute function public.set_updated_at();
create trigger clients_set_updated_at before update on public.clients
for each row execute function public.set_updated_at();
create trigger catalog_items_set_updated_at before update on public."catalogItems"
for each row execute function public.set_updated_at();
create trigger invoices_set_updated_at before update on public.invoices
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public."businessProfiles" enable row level security;
alter table public.clients enable row level security;
alter table public."catalogItems" enable row level security;
alter table public.invoices enable row level security;
alter table public."invoiceItems" enable row level security;
alter table public."invoiceActivities" enable row level security;

comment on table public.users is 'Application user profile. authUserId will link to Supabase Auth during the auth migration.';
comment on function public.set_updated_at() is 'Maintains UTC updatedAt timestamps for Faktur tables.';

commit;
